version: "3.9"
services:
  redis-server:
    image: 'redis:6.2.5-alpine'
    network_mode: 'host'
  database:
    image: 'mysql:8.0'
    network_mode: 'host'
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'Myscretpassword'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'd1105'
      MYSQL_PASSWORD: 'Password123'
    volumes:
      - data:/var/lib/mysql

volumes:
   data:
     external: true


